name: brew pr-pull

on:
  pull_request_target:
    types:
      - labeled

jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      checks: read
      contents: write
      issues: read
      pull-requests: write
    steps:
      - name: Generate a token for the GitHub App
        id: generate-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ vars.BREW_COMMIT_APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Set up Homebrew
        # This repo does not make tags or releases
        uses: Homebrew/actions/setup-homebrew@4ebd32341e5b59ae7e1581111aa99d5d34cef962 # main
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Set up git
        # This repo does not make tags or releases
        uses: Homebrew/actions/git-user-config@4ebd32341e5b59ae7e1581111aa99d5d34cef962 # main

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ steps.generate-token.outputs.token }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: brew pr-pull --debug --tap="$GITHUB_REPOSITORY" "$PULL_REQUEST"

      - name: Push commits
        # This repo does not make tags or releases
        uses: Homebrew/actions/git-try-push@4ebd32341e5b59ae7e1581111aa99d5d34cef962 # main
        with:
          branch: main

      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: git push --delete origin "$BRANCH"
